# Generated by Django 6.0.4 on 2026-04-30 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField()),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], max_length=10)),
                ('exposicion', models.CharField(choices=[('sol', 'Sol pleno'), ('semisombra', 'Semisombra'), ('sombra', 'Sombra')], max_length=15)),
                ('riego', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10)),
                ('meses_siembra', models.CharField(help_text="Ej: 'marzo,abril,mayo'", max_length=50)),
                ('meses_cosecha', models.CharField(help_text="Ej: 'julio,agosto,septiembre'", max_length=50)),
                ('dias_germinacion', models.PositiveIntegerField(blank=True, null=True)),
                ('dias_cosecha', models.PositiveIntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cultivos/')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('nombre_modelo', models.CharField(help_text='Nombre exacto que devuelve el modelo de IA', max_length=150, unique=True)),
                ('descripcion', models.TextField()),
                ('sintomas', models.TextField()),
                ('tratamiento', models.TextField()),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], default='moderada', max_length=10)),
                ('cultivos_afectados', models.ManyToManyField(blank=True, related_name='enfermedades', to='huertosmart.cultivo')),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Huerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(choices=[('balcon', 'Balcón'), ('terraza', 'Terraza'), ('jardin', 'Jardín'), ('parcela', 'Parcela'), ('interior', 'Interior')], max_length=10)),
                ('codigo_postal', models.CharField(blank=True, max_length=5)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('superficie_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Huerto',
                'verbose_name_plural': 'Huertos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField()),
                ('fecha_cosecha_estimada', models.DateField(blank=True, null=True)),
                ('fecha_cosecha_real', models.DateField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Número de plantas')),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('sembrada', 'Sembrada'), ('crecimiento', 'En crecimiento'), ('cosechada', 'Cosechada'), ('perdida', 'Perdida')], default='sembrada', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='huertosmart.cultivo')),
                ('huerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siembras', to='huertosmart.huerto')),
            ],
            options={
                'verbose_name': 'Siembra',
                'verbose_name_plural': 'Siembras',
                'ordering': ['-fecha_siembra'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plaga', 'Plaga'), ('enfermedad', 'Enfermedad'), ('clima', 'Climática'), ('nutricion', 'Nutrición'), ('otro', 'Otra')], max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('siembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='huertosmart.siembra')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='diagnosticos/')),
                ('confianza', models.DecimalField(decimal_places=2, help_text='Porcentaje 0-100', max_digits=5)),
                ('es_planta_valida', models.BooleanField(default=True, help_text='Si Rekognition validó que es una planta')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas_usuario', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to=settings.AUTH_USER_MODEL)),
                ('enfermedad_detectada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='huertosmart.enfermedad')),
                ('siembra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='huertosmart.siembra')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-fecha'],
            },
        ),
    ]
