# Generated by Django 6.0.4 on 2026-05-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huertosmart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='huerto',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
