# Generated by Django 6.0.4 on 2026-05-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huertosmart', '0002_cultivo_slug_huerto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
